language: node_js
node_js: "stable"
sudo: false

addons:
  firefox: latest

script:
  - "npm run-script test"
  - "npm run-script tslint"

deploy:
  provider: npm
  skip_cleanup: true
  email: "bwhmather@bwhmather.com"
  api_key:
    secure: "i9u9y4QN31hAHyTET1S7SKTKgqATq0JAOGdZlXFxdC13QTtAwfZ3eGjwkTMHv+VMCQmkeWeuZEX54rUp80ynaF3dWulg1G+7Mq6ESZG9aUlvIDCFosfOptDNjs0kvg0H1sAuDftAVuuKFwC9RD3CCCEIiqj+OAajk059QZgfnxBGH8azNxyXHC9o4rcMj/nv27PYXckSDZHyXwX83no+7OQHsQf8kt7Qa3fviGHiaieWHh9FBbm2/6x5CYw4a/6TNqt8CzJOkz3gkKZSuV2TNKrGbxHBPa2gKk9X82ioqX9ZVt1Rm6Z09YQfzov/XqtXyzpRG06qKjHuEEZX9LaSSljsuIILa67wjOyJM8t4f0sGg2GsNoLc5mbZl6omt2EVZ7rsrr5ciWCwZfQC3e3eXImoMBv6YWofnX20rosxGx9D4ruUvO+BVEsTVvr2xDVaJpan7M6Tgos6uBRD9RxoUYV5ErqkMRRoCmQsGubHUfkfo43IB/D9+ISpkGC4zT4EkcY0SSh05e21JtoAPMNVntTBlAssmH8cfqaPvwA69cPqQmHH2mmrRLTL6Y/PkKxRmloT0cFfUgOHferGAljpkodb2oiXWe6W1WsTYZ8fvut/lL3wB0uAzX7IsuMX3SpI3LFahscSOe9AmERRj2AQ8pPnrZJs1EDQ7Q9fSoUlGDA="
  on:
    branch: "master"
    tags: true
