name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Publish to npm"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

