name: Testing workflow
on: [push]

jobs:
  test:
    name: "test - ${{ matrix.os }} (${{ matrix.browser }})"

    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chromium, webkit]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Install browser"
        run: npx playwright install --with-deps ${{ matrix.browser }}
      - name: "Compile source files"
        run: npm run build
      - name: "Run tests"
        run: npx playwright test --browser ${{ matrix.browser }}

  lint:
    name: "lint - ${{ matrix.os }}"

    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Run tslint"
        run: npm run tslint

  format:
    name: "format - ${{ matrix.os }}"

    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Run prettier"
        run: npm run prettier
