name: Test
on: [push]

jobs:
  test:
    name: "Test (${{ matrix.browser }})"

    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chromium, webkit]

    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Install browser"
        run: npx playwright install --with-deps ${{ matrix.browser }}
      - name: "Compile source files"
        run: npm run build
      - name: "Run tests"
        run: npx playwright test --browser ${{ matrix.browser }}

  lint:
    name: "Lint"

    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Run tslint"
        run: npm run tslint

  format:
    name: "Format"

    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install NPM dependencies"
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: "Run prettier"
        run: npm run prettier
